In [2]:
import numpy as np

In [7]:
students = np.array([
    ("Ahmed", 16, 92.5),
    ("Sara", 15, 88.0),
    ("Mahmoud", 17, 95.3),
    ("Laila", 16, 90.2)
], dtype=[("name", "U20"), ("age", "i4"), ("grade", "f4")])

In [8]:
students["name"]

array(['Ahmed', 'Sara', 'Mahmoud', 'Laila'], dtype='<U20')

In [9]:
students["age"]

array([16, 15, 17, 16], dtype=int32)

In [10]:
students["grade"]

array([92.5, 88. , 95.3, 90.2], dtype=float32)

In [13]:
students[students["name"] == "Ahmed"]["age"]

array([16], dtype=int32)